name: Anypoint CLI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cli:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4
        
      - name: Config Organization
        run: >
          anypoint-cli-v4 conf organization 29fcc50f-0380-4b40-ad8b-d7773ae5398f

      - name: Config Client Id
        run: >
          anypoint-cli-v4 conf client_id 80d66a6539aa4276b43d6125695d42a6

      - name: Config Client Secret
        run: >
          anypoint-cli-v4 conf client_secret 34750839f3654308A67a6fA85a8f7a1a

      - name: List All Mule Apps
        run: >
          anypoint-cli-v4 runtime-mgr:application:list --environment Sandbox
