name: Anypoint CLI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cli:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4
        
      - name: Config Organization
        run: >
          anypoint-cli-v4 conf organization 27127d7e-518e-48e7-b7e3-0dbf2c5475bf

      - name: Config Client Id
        run: >
          anypoint-cli-v4 conf client_id b23364a06f0443ea806b61179a810a2c

      - name: Config Client Secret
        run: >
          anypoint-cli-v4 conf client_secret 4B8b2070986E4a32A6c2E6c89770139E

      - name: Config Environment
        run: >
          anypoint-cli-v4 conf environment Sandbox

      - name: List All Mule Apps
        run: >
          anypoint-cli-v4 runtime-mgr:application:list --environment Sandbox

      - name: Lists all assets for our Organization
        run: >
          anypoint-cli-v4 exchange:asset:list --organizationId 27127d7e-518e-48e7-b7e3-0dbf2c5475bf --output json
